baseurl      = "https://tzero86bits.tk/"
title        = "tzero86.bits"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10
googleAnalytics = "UA-175520987-1"
disqusShortname = "tzero86bits"


[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  showMenuItems = true
  # Subtitle for home
  homeSubtitle = "hacking notes, tools and rants."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you linke
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "hacking notes and rants"
  keywords = "homepage, blog, hacking, ethical hacking, pentesting, tryhackme, writeups"
  images = [""]

  # Default theme "light" or "dark"
  defaultTheme = "dark"

  twitterLink = "https://twitter.com/Tzero86"

[languages]
  [languages.en]
    title = "tzero86.bits"
    subtitle = "hacking notes, tools and rants."
    keywords = "hacking, ethical hacking, pentesting, tryhackme, writeups"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "tzero86.bits"
      logoHomeLink = "/"
      #path = "./hacker.svg"
      #alt = "Your example logo alt text"
    # or
    #
    

  # And you can even create generic menu
  

  [[menu.main]]
    identifier = "blog"
    name       = "/Posts"
    url        = "/posts/"

  [[menu.main]]
    identifier = "page"
    name       = "/About"
    url        = "/page/about/"


  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/Tzero86"

  [[params.social]]
    name = "github"
    url = "https://github.com/Tzero86"